name: Semantic PRs
on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true
permissions:
  pull-requests: write
jobs:
  validate_title:
    name: Validate Title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            ac
            wa
            tle
            cs
          scopes: |
            [a-zA-Z0-9_-]{1,39}
          requireScope: true
          subjectPattern: '^\d{2}-\d{2}-\d{4}$'
          subjectPatternError: |
            The date in the PR title must follow the format dd-mm-yyyy (e.g., 04-01-2025).
